name: Publish Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.GITHUB_REPOSITORY }}:latest
          # Use a more specific tag if desired (e.g., ${{ secrets.GITHUB_REPOSITORY }}:v1.0.0)
        env:
          DOCKER_HOST: unix:///var/run/docker.sock
          DOCKER_TLS_CERTDIR: ''
          DOCKER_USERNAME: ${{ secrets.GITHUB_ACTOR }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
